from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bd123824880'
down_revision: Union[str, Sequence[str], None] = '1fea9f478b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###

    op.create_table(
        'refresh_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('is_revoked', sa.Boolean(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)

    op.add_column(
        'albums',
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()'))
    )
    op.alter_column(
        'albums',
        'artist_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'albums',
        'release_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        existing_nullable=True
    )
    op.alter_column(
        'albums',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False
    )
    op.create_index(op.f('ix_albums_artist_id'), 'albums', ['artist_id'], unique=False)
    op.create_unique_constraint('uq_albums_artist_title', 'albums', ['artist_id', 'title'])

    op.add_column(
        'artists',
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()'))
    )
    op.alter_column(
        'artists',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False
    )
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=True)

    op.alter_column(
        'favorite_songs',
        'user_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'favorite_songs',
        'song_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'favorite_songs',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False
    )
    op.create_index(op.f('ix_favorite_songs_song_id'), 'favorite_songs', ['song_id'], unique=False)
    op.create_index(op.f('ix_favorite_songs_user_id'), 'favorite_songs', ['user_id'], unique=False)
    op.create_unique_constraint('uq_favorite_songs_user_song', 'favorite_songs', ['user_id', 'song_id'])

    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)

    op.alter_column(
        'play_history',
        'user_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'play_history',
        'song_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'play_history',
        'played_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False
    )
    op.alter_column(
        'play_history',
        'seconds_listened',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.create_index(op.f('ix_play_history_song_id'), 'play_history', ['song_id'], unique=False)
    op.create_index(op.f('ix_play_history_user_id'), 'play_history', ['user_id'], unique=False)

    op.alter_column(
        'playlist_songs',
        'playlist_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'playlist_songs',
        'song_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'playlist_songs',
        'position',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'playlist_songs',
        'added_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False
    )
    op.create_index(op.f('ix_playlist_songs_playlist_id'), 'playlist_songs', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_songs_song_id'), 'playlist_songs', ['song_id'], unique=False)
    op.create_unique_constraint('uq_playlist_songs_playlist_position', 'playlist_songs', ['playlist_id', 'position'])
    op.create_unique_constraint('uq_playlist_songs_playlist_song', 'playlist_songs', ['playlist_id', 'song_id'])

    op.alter_column(
        'playlists',
        'user_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'playlists',
        'is_public',
        existing_type=sa.BOOLEAN(),
        nullable=False
    )
    op.alter_column(
        'playlists',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False
    )
    op.alter_column(
        'playlists',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False
    )
    op.create_index(op.f('ix_playlists_user_id'), 'playlists', ['user_id'], unique=False)

    op.alter_column(
        'search_history',
        'user_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'search_history',
        'query',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    op.alter_column(
        'search_history',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False
    )
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)

    op.add_column(
        'songs',
        sa.Column('audio_path', sa.String(), nullable=False, server_default='')
    )
    op.add_column(
        'songs',
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()'))
    )
    op.alter_column(
        'songs',
        'album_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'songs',
        'duration_seconds',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'songs',
        'track_number',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'songs',
        'plays_count',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'songs',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False
    )
    op.create_index(op.f('ix_songs_album_id'), 'songs', ['album_id'], unique=False)
    op.create_index(op.f('ix_songs_title'), 'songs', ['title'], unique=False)
    op.create_unique_constraint('uq_songs_album_track_number', 'songs', ['album_id', 'track_number'])
    op.drop_column('songs', 'audio_url')

    op.add_column(
        'users',
        sa.Column('role', sa.String(length=20), nullable=False, server_default='user')
    )
    op.add_column(
        'users',
        sa.Column('auth_provider', sa.String(length=20), nullable=False, server_default='local')
    )
    op.add_column(
        'users',
        sa.Column('provider_user_id', sa.String(length=255), nullable=True)
    )
    op.add_column(
        'users',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true())
    )
    op.add_column(
        'users',
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column(
        'users',
        'password_hash',
        existing_type=sa.VARCHAR(),
        nullable=True
    )
    op.alter_column(
        'users',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False
    )
    op.alter_column(
        'users',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False
    )
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_auth_provider'), 'users', ['auth_provider'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_provider_user_id'), 'users', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # Quitar defaults temporales
    op.alter_column('albums', 'updated_at', server_default=None)
    op.alter_column('artists', 'updated_at', server_default=None)
    op.alter_column('songs', 'audio_path', server_default=None)
    op.alter_column('songs', 'updated_at', server_default=None)
    op.alter_column('users', 'role', server_default=None)
    op.alter_column('users', 'auth_provider', server_default=None)
    op.alter_column('users', 'is_active', server_default=None)
    op.alter_column('users', 'is_verified', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_provider_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_provider'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column(
        'users',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True
    )
    op.alter_column(
        'users',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True
    )
    op.alter_column(
        'users',
        'password_hash',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'provider_user_id')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'role')

    op.add_column('songs', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_songs_album_track_number', 'songs', type_='unique')
    op.drop_index(op.f('ix_songs_title'), table_name='songs')
    op.drop_index(op.f('ix_songs_album_id'), table_name='songs')
    op.alter_column(
        'songs',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True
    )
    op.alter_column(
        'songs',
        'plays_count',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'songs',
        'track_number',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'songs',
        'duration_seconds',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'songs',
        'album_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.drop_column('songs', 'updated_at')
    op.drop_column('songs', 'audio_path')

    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.alter_column(
        'search_history',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True
    )
    op.alter_column(
        'search_history',
        'query',
        existing_type=sa.VARCHAR(),
        nullable=True
    )
    op.alter_column(
        'search_history',
        'user_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )

    op.drop_index(op.f('ix_playlists_user_id'), table_name='playlists')
    op.alter_column(
        'playlists',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True
    )
    op.alter_column(
        'playlists',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True
    )
    op.alter_column(
        'playlists',
        'is_public',
        existing_type=sa.BOOLEAN(),
        nullable=True
    )
    op.alter_column(
        'playlists',
        'user_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )

    op.drop_constraint('uq_playlist_songs_playlist_song', 'playlist_songs', type_='unique')
    op.drop_constraint('uq_playlist_songs_playlist_position', 'playlist_songs', type_='unique')
    op.drop_index(op.f('ix_playlist_songs_song_id'), table_name='playlist_songs')
    op.drop_index(op.f('ix_playlist_songs_playlist_id'), table_name='playlist_songs')
    op.alter_column(
        'playlist_songs',
        'added_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True
    )
    op.alter_column(
        'playlist_songs',
        'position',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'playlist_songs',
        'song_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'playlist_songs',
        'playlist_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )

    op.drop_index(op.f('ix_play_history_user_id'), table_name='play_history')
    op.drop_index(op.f('ix_play_history_song_id'), table_name='play_history')
    op.alter_column(
        'play_history',
        'seconds_listened',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'play_history',
        'played_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True
    )
    op.alter_column(
        'play_history',
        'song_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'play_history',
        'user_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )

    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')

    op.drop_constraint('uq_favorite_songs_user_song', 'favorite_songs', type_='unique')
    op.drop_index(op.f('ix_favorite_songs_user_id'), table_name='favorite_songs')
    op.drop_index(op.f('ix_favorite_songs_song_id'), table_name='favorite_songs')
    op.alter_column(
        'favorite_songs',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True
    )
    op.alter_column(
        'favorite_songs',
        'song_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'favorite_songs',
        'user_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )

    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.alter_column(
        'artists',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True
    )
    op.drop_column('artists', 'updated_at')

    op.drop_constraint('uq_albums_artist_title', 'albums', type_='unique')
    op.drop_index(op.f('ix_albums_artist_id'), table_name='albums')
    op.alter_column(
        'albums',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True
    )
    op.alter_column(
        'albums',
        'release_date',
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True
    )
    op.alter_column(
        'albums',
        'artist_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.drop_column('albums', 'updated_at')

    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###