"""add user_id to artists

Revision ID: ee108163da7a
Revises: 1bd123824880
Create Date: 2026-03-13 21:01:53.464722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee108163da7a'
down_revision: Union[str, Sequence[str], None] = '1bd123824880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_artists_user_id'), 'artists', ['user_id'], unique=True)
    op.create_foreign_key(None, 'artists', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_index(op.f('ix_artists_user_id'), table_name='artists')
    op.drop_column('artists', 'user_id')
    # ### end Alembic commands ###
